// 菜谱数据库
const DISH_DATABASE = {
    // 荤菜
    meat: [
        {
            id: 'm1',
            name: '清蒸鲈鱼',
            category: 'meat',
            tags: ['海鲜', '清淡', '蒸'],
            ingredients: ['鲈鱼', '姜', '葱', '料酒', '生抽'],
            time: '20分钟',
            difficulty: '简单',
            method: '鲈鱼洗净划刀，放姜片葱段，蒸8-10分钟，淋生抽热油',
            note: '周末推荐',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 'm2',
            name: '番茄炒蛋',
            category: 'meat',
            tags: ['快手', '家常', '炒'],
            ingredients: ['西红柿', '鸡蛋', '葱', '盐', '糖'],
            time: '10分钟',
            difficulty: '简单',
            method: '番茄切块，鸡蛋打散炒熟盛出，炒番茄出汁，回锅鸡蛋，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'm3',
            name: '青椒炒培根',
            category: 'meat',
            tags: ['快手', '炒', '西式'],
            ingredients: ['青椒', '培根', '蒜', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '培根切小块，青椒切丝，先炒培根出油，再炒青椒，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'm4',
            name: '清蒸鳕鱼',
            category: 'meat',
            tags: ['海鲜', '清淡', '蒸'],
            ingredients: ['鳕鱼', '姜', '葱', '料酒', '生抽'],
            time: '15分钟',
            difficulty: '简单',
            method: '鳕鱼解冻，放姜片，蒸8分钟，淋生抽热油',
            note: '冷冻食材可用',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 'm5',
            name: '清蒸三文鱼',
            category: 'meat',
            tags: ['海鲜', '清淡', '蒸'],
            ingredients: ['三文鱼', '柠檬', '黑胡椒', '盐'],
            time: '15分钟',
            difficulty: '简单',
            method: '三文鱼解冻，撒盐和黑胡椒，蒸10分钟，挤柠檬汁',
            note: '冷冻食材可用',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 'm6',
            name: '香煎鳕鱼',
            category: 'meat',
            tags: ['海鲜', '煎', '少油'],
            ingredients: ['鳕鱼', '黄油', '黑胡椒', '盐', '柠檬'],
            time: '15分钟',
            difficulty: '简单',
            method: '鳕鱼解冻擦干，少油小火煎至两面金黄，撒黑胡椒盐，挤柠檬',
            note: '少油健康做法',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 'm7',
            name: '肥牛卷炒洋葱',
            category: 'meat',
            tags: ['快手', '炒', '牛肉'],
            ingredients: ['肥牛卷', '洋葱', '生抽', '料酒', '糖'],
            time: '15分钟',
            difficulty: '简单',
            method: '洋葱切丝，肥牛焯水捞出，炒洋葱软化，加肥牛和调料炒匀',
            note: '冷冻食材可用',
            forbidden: []
        },
        {
            id: 'm8',
            name: '肥牛卷炒青椒',
            category: 'meat',
            tags: ['快手', '炒', '牛肉'],
            ingredients: ['肥牛卷', '青椒', '生抽', '料酒', '蒜'],
            time: '15分钟',
            difficulty: '简单',
            method: '青椒切丝，肥牛焯水，蒜爆香，炒青椒和肥牛，加生抽调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'm9',
            name: '葱姜排骨',
            category: 'meat',
            tags: ['预制', '加热即可', '猪肉'],
            ingredients: ['排骨（预制）', '葱', '姜'],
            time: '10分钟',
            difficulty: '简单',
            method: '冷冻预制排骨加热即可，可撒新鲜葱花增香',
            note: '冷冻现成，加热即食',
            forbidden: ['排骨汤']
        },
        {
            id: 'm10',
            name: '清蒸乌鸡',
            category: 'meat',
            tags: ['蒸', '鸡肉', '清淡'],
            ingredients: ['乌鸡', '姜', '葱', '枸杞', '盐'],
            time: '40分钟',
            difficulty: '中等',
            method: '乌鸡解冻洗净，放姜片葱段，蒸40分钟，出锅撒枸杞',
            note: '不做乌鸡汤，改为清蒸',
            forbidden: ['乌鸡汤']
        },
        {
            id: 'm11',
            name: '红烧乌鸡',
            category: 'meat',
            tags: ['红烧', '鸡肉'],
            ingredients: ['乌鸡', '生抽', '老抽', '糖', '姜', '葱'],
            time: '45分钟',
            difficulty: '中等',
            method: '乌鸡切块焯水，少油炒糖色，下鸡块翻炒，加生抽老抽水，焖煮30分钟',
            note: '少油版红烧',
            forbidden: ['乌鸡汤']
        },
        {
            id: 'm12',
            name: '芦笋炒虾仁',
            category: 'meat',
            tags: ['海鲜', '炒', '清淡'],
            ingredients: ['芦笋', '虾仁', '蒜', '盐', '黑胡椒'],
            time: '15分钟',
            difficulty: '简单',
            method: '芦笋切段焯水，虾仁解冻，蒜爆香，炒虾仁变色，加芦笋调味',
            note: '清淡健康',
            forbidden: []
        },
        {
            id: 'm13',
            name: '蒜苔炒培根',
            category: 'meat',
            tags: ['快手', '炒'],
            ingredients: ['蒜苔', '培根', '蒜', '生抽'],
            time: '15分钟',
            difficulty: '简单',
            method: '蒜苔切段，培根切小块，先炒培根出油，再炒蒜苔，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'm14',
            name: '洋葱炒牛肉',
            category: 'meat',
            tags: ['炒', '牛肉'],
            ingredients: ['牛肉', '洋葱', '生抽', '料酒', '黑胡椒'],
            time: '15分钟',
            difficulty: '简单',
            method: '牛肉切片，洋葱切丝，牛肉炒至变色盛出，炒洋葱软化，回锅牛肉，调味',
            note: '可用冷冻牛肉',
            forbidden: []
        },
        {
            id: 'm15',
            name: '黑椒牛柳',
            category: 'meat',
            tags: ['炒', '牛肉', '西式'],
            ingredients: ['牛肉', '青椒', '洋葱', '黑胡椒', '生抽'],
            time: '20分钟',
            difficulty: '中等',
            method: '牛肉切条腌制，青椒洋葱切丝，先炒牛肉盛出，炒配菜，回锅调味',
            note: '需要腌制',
            forbidden: []
        },
        {
            id: 'm16',
            name: '爆炒鱿鱼',
            category: 'meat',
            tags: ['海鲜', '炒', '快手'],
            ingredients: ['鱿鱼', '青椒', '洋葱', '姜', '料酒', '生抽'],
            time: '10分钟',
            difficulty: '简单',
            method: '鱿鱼解冻切花刀焯水，青椒洋葱切丝，大火爆炒，调味出锅',
            note: '冷冻鱿鱼可用',
            forbidden: []
        },
        {
            id: 'm17',
            name: '鱿鱼炒韭菜',
            category: 'meat',
            tags: ['海鲜', '炒'],
            ingredients: ['鱿鱼', '韭菜', '姜', '料酒', '生抽'],
            time: '12分钟',
            difficulty: '简单',
            method: '鱿鱼解冻切条焯水，韭菜切段，大火爆炒，调味',
            note: '经典搭配',
            forbidden: []
        },
        {
            id: 'm18',
            name: '香煎三文鱼',
            category: 'meat',
            tags: ['海鲜', '煎'],
            ingredients: ['三文鱼', '黄油', '柠檬', '黑胡椒', '盐'],
            time: '15分钟',
            difficulty: '简单',
            method: '三文鱼擦干，黄油中小火煎至两面金黄，撒盐和黑胡椒，挤柠檬',
            note: '外酥里嫩',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 'm19',
            name: '烤鸡翅',
            category: 'meat',
            tags: ['烤', '鸡肉'],
            ingredients: ['鸡翅', '生抽', '蚝油', '蜂蜜', '蒜', '黑胡椒'],
            time: '40分钟',
            difficulty: '简单',
            method: '鸡翅划刀腌制30分钟，烤箱200度烤25分钟，中途刷蜂蜜水',
            note: '需要烤箱',
            forbidden: []
        },
        {
            id: 'm20',
            name: '可乐鸡翅',
            category: 'meat',
            tags: ['炖', '鸡肉', '甜口'],
            ingredients: ['鸡翅', '可乐', '生抽', '老抽', '姜'],
            time: '30分钟',
            difficulty: '简单',
            method: '鸡翅焯水，煎至金黄，加可乐和调料，小火炖20分钟收汁',
            note: '孩子爱吃',
            forbidden: []
        },
        {
            id: 'm21',
            name: '蒜蓉粉丝蒸虾',
            category: 'meat',
            tags: ['海鲜', '蒸'],
            ingredients: ['虾', '粉丝', '蒜蓉', '生抽', '葱'],
            time: '15分钟',
            difficulty: '简单',
            method: '粉丝泡软铺底，虾去虾线摆盘，撒蒜蓉，蒸8分钟，淋生抽热油',
            note: '鲜香味美',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 'm22',
            name: '白灼虾',
            category: 'meat',
            tags: ['海鲜', '清淡'],
            ingredients: ['虾', '姜', '葱', '料酒', '生抽'],
            time: '10分钟',
            difficulty: '简单',
            method: '水加姜葱料酒烧开，放入虾煮2-3分钟变色，蘸生抽',
            note: '最鲜美的做法',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 'm23',
            name: '红烧肉',
            category: 'meat',
            tags: ['红烧', '猪肉', '经典'],
            ingredients: ['五花肉', '生抽', '老抽', '冰糖', '姜', '八角'],
            time: '60分钟',
            difficulty: '中等',
            method: '五花肉切块焯水，炒糖色，下肉翻炒，加调料和水，小火炖45分钟',
            note: '经典家常菜',
            forbidden: []
        },
        {
            id: 'm24',
            name: '糖醋排骨',
            category: 'meat',
            tags: ['糖醋', '猪肉'],
            ingredients: ['排骨', '糖', '醋', '生抽', '料酒', '姜'],
            time: '50分钟',
            difficulty: '中等',
            method: '排骨焯水，煎至金黄，加糖醋汁和水，小火炖40分钟收汁',
            note: '酸甜可口',
            forbidden: ['排骨汤']
        },
        {
            id: 'm25',
            name: '粉蒸肉',
            category: 'meat',
            tags: ['蒸', '猪肉'],
            ingredients: ['五花肉', '蒸肉米粉', '生抽', '料酒', '姜'],
            time: '60分钟',
            difficulty: '中等',
            method: '五花肉切片腌制，裹蒸肉米粉，铺盘蒸60分钟',
            note: '软糯香嫩',
            forbidden: []
        },
        {
            id: 'm26',
            name: '狮子头',
            category: 'meat',
            tags: ['炖', '猪肉'],
            ingredients: ['猪肉馅', '鸡蛋', '淀粉', '生抽', '葱', '姜'],
            time: '60分钟',
            difficulty: '中等',
            method: '肉馅加调料搅打上劲，做成大丸子，煎至定型，加水炖煮',
            note: '需要肉馅',
            forbidden: ['红烧狮子头']
        },
        {
            id: 'm27',
            name: '肉末蒸蛋',
            category: 'meat',
            tags: ['蒸', '快手'],
            ingredients: ['猪肉馅', '鸡蛋', '生抽', '葱', '香油'],
            time: '20分钟',
            difficulty: '简单',
            method: '鸡蛋打散加温水，先蒸10分钟定型，加炒熟的肉末，再蒸5分钟',
            note: '嫩滑下饭',
            forbidden: []
        },
        {
            id: 'm28',
            name: '蚂蚁上树',
            category: 'meat',
            tags: ['炒', '粉丝'],
            ingredients: ['猪肉馅', '粉丝', '豆瓣酱', '葱', '姜'],
            time: '20分钟',
            difficulty: '简单',
            method: '粉丝泡软，肉馅炒熟，加豆瓣酱炒香，加粉丝拌匀',
            note: '麻辣鲜香',
            forbidden: []
        },
        {
            id: 'm29',
            name: '宫保鸡丁',
            category: 'meat',
            tags: ['炒', '鸡肉', '经典'],
            ingredients: ['鸡胸肉', '花生米', '干辣椒', '葱', '生抽', '醋', '糖'],
            time: '25分钟',
            difficulty: '中等',
            method: '鸡肉切丁腌制，炒熟盛出，炒香辣椒花生，回锅鸡丁，淋宫保汁',
            note: '经典川菜',
            forbidden: []
        },
        {
            id: 'm30',
            name: '辣子鸡',
            category: 'meat',
            tags: ['炸', '鸡肉', '辣'],
            ingredients: ['鸡肉', '干辣椒', '花椒', '葱', '姜', '料酒'],
            time: '40分钟',
            difficulty: '中等',
            method: '鸡肉切块腌制，炸至金黄，炒香辣椒花椒，下鸡块炒匀',
            note: '麻辣干香',
            forbidden: []
        },
        {
            id: 'm31',
            name: '口水鸡',
            category: 'meat',
            tags: ['凉拌', '鸡肉'],
            ingredients: ['鸡腿', '辣椒油', '花椒粉', '生抽', '醋', '蒜', '花生碎'],
            time: '30分钟',
            difficulty: '中等',
            method: '鸡腿煮熟冰镇，撕成丝，淋上调好的红油酱汁，撒花生',
            note: '麻辣鲜香',
            forbidden: ['凉拌黄瓜']
        },
        {
            id: 'm32',
            name: '咖喱鸡肉',
            category: 'meat',
            tags: ['炖', '鸡肉', '咖喱'],
            ingredients: ['鸡肉', '土豆', '洋葱', '胡萝卜', '咖喱块'],
            time: '40分钟',
            difficulty: '简单',
            method: '鸡肉切块炒熟，加蔬菜翻炒，加水和咖喱块，炖20分钟',
            note: '浓郁下饭',
            forbidden: []
        },
        {
            id: 'm33',
            name: '照烧鸡腿',
            category: 'meat',
            tags: ['煎', '鸡肉', '日式'],
            ingredients: ['鸡腿', '生抽', '料酒', '蜂蜜', '姜'],
            time: '30分钟',
            difficulty: '简单',
            method: '鸡腿去骨煎至金黄，倒入照烧汁，小火焖10分钟收汁',
            note: '甜咸适口',
            forbidden: []
        },
        {
            id: 'm34',
            name: '酸菜鱼',
            category: 'meat',
            tags: ['煮', '鱼片'],
            ingredients: ['鱼片', '酸菜', '泡椒', '姜', '花椒', '辣椒'],
            time: '30分钟',
            difficulty: '中等',
            method: '鱼片腌制，炒香酸菜泡椒，加水煮开，下鱼片煮熟',
            note: '酸辣开胃',
            forbidden: ['鱼汤']
        },
        {
            id: 'm35',
            name: '水煮肉片',
            category: 'meat',
            tags: ['煮', '猪肉', '辣'],
            ingredients: ['猪肉片', '豆芽', '干辣椒', '花椒', '豆瓣酱', '姜', '蒜'],
            time: '30分钟',
            difficulty: '中等',
            method: '肉片腌制，炒香豆瓣酱加水煮开，下肉片和蔬菜，淋热油',
            note: '麻辣鲜香',
            forbidden: ['干锅']
        },
        {
            id: 'm36',
            name: '鱼香肉丝',
            category: 'meat',
            tags: ['炒', '猪肉', '经典'],
            ingredients: ['猪肉丝', '木耳', '笋丝', '胡萝卜', '豆瓣酱', '生抽', '醋', '糖'],
            time: '25分钟',
            difficulty: '中等',
            method: '肉丝腌制炒熟盛出，炒香豆瓣酱和配菜，回锅肉丝，淋鱼香汁',
            note: '鱼香味型',
            forbidden: []
        },
        {
            id: 'm37',
            name: '青椒肉丝',
            category: 'meat',
            tags: ['炒', '猪肉', '快手'],
            ingredients: ['猪肉丝', '青椒', '生抽', '料酒', '淀粉'],
            time: '15分钟',
            difficulty: '简单',
            method: '肉丝腌制炒至变色盛出，炒青椒，回锅肉丝，调味',
            note: '家常快手',
            forbidden: []
        },
        {
            id: 'm38',
            name: '回锅肉',
            category: 'meat',
            tags: ['炒', '猪肉', '经典'],
            ingredients: ['五花肉', '青椒', '豆瓣酱', '生抽', '糖'],
            time: '25分钟',
            difficulty: '中等',
            method: '五花肉煮熟切片，煎至出油卷起，加豆瓣酱炒香，加青椒炒匀',
            note: '川菜经典',
            forbidden: ['回锅肉']
        },
        {
            id: 'm39',
            name: '韭菜炒蛋',
            category: 'meat',
            tags: ['炒', '蛋', '快手'],
            ingredients: ['韭菜', '鸡蛋', '盐'],
            time: '8分钟',
            difficulty: '简单',
            method: '韭菜切段，鸡蛋炒熟盛出，炒韭菜，回锅鸡蛋，调味',
            note: '简单美味',
            forbidden: []
        },
        {
            id: 'm40',
            name: '虾仁炒蛋',
            category: 'meat',
            tags: ['炒', '海鲜', '蛋'],
            ingredients: ['虾仁', '鸡蛋', '葱', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '虾仁解冻，鸡蛋打散，先炒虾仁，倒入蛋液炒熟',
            note: '嫩滑鲜美',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 'm41',
            name: '滑蛋牛肉',
            category: 'meat',
            tags: ['炒', '牛肉', '粤菜'],
            ingredients: ['牛肉', '鸡蛋', '生抽', '淀粉', '油'],
            time: '15分钟',
            difficulty: '中等',
            method: '牛肉腌制炒至变色盛出，鸡蛋打散，倒入牛肉，小火推熟',
            note: '嫩滑无比',
            forbidden: []
        },
        {
            id: 'm42',
            name: '黑椒牛排',
            category: 'meat',
            tags: ['煎', '牛肉', '西式'],
            ingredients: ['牛排', '黑胡椒', '盐', '黄油', '蒜'],
            time: '15分钟',
            difficulty: '简单',
            method: '牛排回温，撒盐和黑胡椒，热锅煎3-4分钟每面，加黄油蒜瓣',
            note: '需要牛排',
            forbidden: []
        },
        {
            id: 'm43',
            name: '番茄牛腩',
            category: 'meat',
            tags: ['炖', '牛肉', '番茄'],
            ingredients: ['牛腩', '西红柿', '洋葱', '生抽', '料酒', '姜'],
            time: '90分钟',
            difficulty: '中等',
            method: '牛腩焯水，炒番茄出汁，加牛腩和水，小火炖1.5小时',
            note: '软烂入味',
            forbidden: []
        },
        {
            id: 'm44',
            name: '酱牛肉',
            category: 'meat',
            tags: ['卤', '牛肉'],
            ingredients: ['牛腱子', '生抽', '老抽', '料酒', '八角', '桂皮', '姜'],
            time: '120分钟',
            difficulty: '中等',
            method: '牛肉焯水，加所有调料和水，小火卤2小时，浸泡过夜',
            note: '冷吃更佳',
            forbidden: []
        },
        {
            id: 'm45',
            name: '猪肚炒青椒',
            category: 'meat',
            tags: ['炒', '猪肚'],
            ingredients: ['猪肚', '青椒', '蒜', '生抽', '料酒'],
            time: '20分钟',
            difficulty: '简单',
            method: '猪肚切丝焯水，青椒切丝，蒜爆香，同炒调味',
            note: '冷冻猪肚可用',
            forbidden: []
        },
        {
            id: 'm46',
            name: '猪肚鸡',
            category: 'meat',
            tags: ['炖', '猪肚', '鸡肉'],
            ingredients: ['猪肚', '鸡肉', '姜', '葱', '胡椒'],
            time: '90分钟',
            difficulty: '中等',
            method: '猪肚洗净焯水，鸡肉焯水，一起炖煮1.5小时，调味',
            note: '滋补暖胃',
            forbidden: ['鸡汤', '鸭汤', '鱼汤']
        },
        {
            id: 'm47',
            name: '爆炒猪肝',
            category: 'meat',
            tags: ['炒', '猪肝'],
            ingredients: ['猪肝', '青椒', '洋葱', '姜', '料酒', '生抽'],
            time: '15分钟',
            difficulty: '中等',
            method: '猪肝切片腌制，焯水去血，大火爆炒配菜，快速翻炒出锅',
            note: '补血佳品',
            forbidden: []
        },
        {
            id: 'm48',
            name: '卤蛋',
            category: 'meat',
            tags: ['卤', '蛋'],
            ingredients: ['鸡蛋', '生抽', '老抽', '八角', '桂皮', '茶叶'],
            time: '40分钟',
            difficulty: '简单',
            method: '鸡蛋煮熟剥壳，加所有调料和水，小火煮30分钟，浸泡入味',
            note: '提前准备',
            forbidden: []
        },
        {
            id: 'm49',
            name: '煎蛋',
            category: 'meat',
            tags: ['煎', '蛋', '快手'],
            ingredients: ['鸡蛋', '盐', '油'],
            time: '3分钟',
            difficulty: '简单',
            method: '热锅少油，打入鸡蛋，小火煎至蛋白凝固，撒盐',
            note: '最简单',
            forbidden: []
        },
        {
            id: 'm50',
            name: '蒸蛋羹',
            category: 'meat',
            tags: ['蒸', '蛋', '清淡'],
            ingredients: ['鸡蛋', '温水', '盐', '生抽', '香油'],
            time: '15分钟',
            difficulty: '简单',
            method: '鸡蛋打散加温水和盐，过滤气泡，蒸12分钟，淋生抽香油',
            note: '嫩滑如豆腐',
            forbidden: []
        },
        {
            id: 'm51',
            name: '糖醋里脊',
            category: 'meat',
            tags: ['糖醋', '猪肉'],
            ingredients: ['里脊肉', '糖', '醋', '生抽', '料酒', '淀粉'],
            time: '30分钟',
            difficulty: '中等',
            method: '里脊切条腌制，裹淀粉炸至金黄，淋糖醋汁',
            note: '酸甜可口',
            forbidden: ['糖醋里脊']
        },
        {
            id: 'm52',
            name: '锅包肉',
            category: 'meat',
            tags: ['炸', '猪肉', '东北菜'],
            ingredients: ['里脊肉', '糖', '醋', '生抽', '淀粉', '胡萝卜', '葱'],
            time: '40分钟',
            difficulty: '中等',
            method: '里脊切片腌制，裹淀粉炸至酥脆，淋糖醋汁，加配菜',
            note: '外酥里嫩',
            forbidden: []
        },
        {
            id: 'm53',
            name: '京酱肉丝',
            category: 'meat',
            tags: ['炒', '猪肉', '北京菜'],
            ingredients: ['里脊肉', '甜面酱', '葱', '黄瓜', '豆皮'],
            time: '25分钟',
            difficulty: '中等',
            method: '肉丝炒熟，加甜面酱炒香，配葱丝黄瓜丝豆皮卷食',
            note: '经典北京菜',
            forbidden: []
        },
        {
            id: 'm54',
            name: '木须肉',
            category: 'meat',
            tags: ['炒', '猪肉', '经典'],
            ingredients: ['猪肉', '鸡蛋', '木耳', '黄瓜', '生抽'],
            time: '20分钟',
            difficulty: '简单',
            method: '肉片炒熟，鸡蛋炒熟，加木耳黄瓜炒匀，调味',
            note: '营养丰富',
            forbidden: []
        },
        {
            id: 'm55',
            name: '农家小炒肉',
            category: 'meat',
            tags: ['炒', '猪肉', '辣'],
            ingredients: ['五花肉', '青椒', '豆豉', '蒜', '生抽'],
            time: '20分钟',
            difficulty: '简单',
            method: '五花肉片煎至出油，加豆豉蒜爆香，加青椒炒匀',
            note: '下饭神器',
            forbidden: []
        },
        {
            id: 'm56',
            name: '梅菜扣肉',
            category: 'meat',
            tags: ['蒸', '猪肉', '经典'],
            ingredients: ['五花肉', '梅干菜', '生抽', '老抽', '糖', '料酒'],
            time: '120分钟',
            difficulty: '困难',
            method: '五花肉煮熟炸皮，切片码碗，铺梅菜，蒸2小时倒扣',
            note: '宴席大菜',
            forbidden: []
        },
        {
            id: 'm57',
            name: '东坡肉',
            category: 'meat',
            tags: ['炖', '猪肉', '经典'],
            ingredients: ['五花肉', '生抽', '老抽', '冰糖', '料酒', '葱', '姜'],
            time: '120分钟',
            difficulty: '中等',
            method: '五花肉切块焯水，炒糖色，加调料小火炖2小时',
            note: '肥而不腻',
            forbidden: []
        },
        {
            id: 'm58',
            name: '卤肉饭',
            category: 'meat',
            tags: ['炖', '猪肉', '主食'],
            ingredients: ['五花肉', '洋葱', '生抽', '老抽', '冰糖', '五香粉'],
            time: '90分钟',
            difficulty: '中等',
            method: '五花肉切丁，洋葱炸酥，加调料炖1小时，配米饭',
            note: '台湾经典',
            forbidden: []
        },
        {
            id: 'm59',
            name: '蒜泥白肉',
            category: 'meat',
            tags: ['凉拌', '猪肉'],
            ingredients: ['五花肉', '蒜', '生抽', '醋', '辣椒油', '黄瓜'],
            time: '40分钟',
            difficulty: '简单',
            method: '五花肉煮熟切片，配蒜泥酱汁，垫黄瓜片',
            note: '清爽开胃',
            forbidden: ['凉拌黄瓜']
        },
        {
            id: 'm60',
            name: '盐煎肉',
            category: 'meat',
            tags: ['炒', '猪肉'],
            ingredients: ['五花肉', '青椒', '豆瓣酱', '豆豉', '生抽'],
            time: '20分钟',
            difficulty: '简单',
            method: '五花肉片干煎至出油，加豆瓣酱豆豉炒香，加青椒',
            note: '干香下饭',
            forbidden: []
        },
        {
            id: 'm61',
            name: '椒盐排骨',
            category: 'meat',
            tags: ['炸', '猪肉'],
            ingredients: ['排骨', '椒盐', '蒜', '料酒', '生抽', '淀粉'],
            time: '40分钟',
            difficulty: '中等',
            method: '排骨腌制，裹淀粉炸至金黄，撒椒盐',
            note: '香酥可口',
            forbidden: ['排骨汤']
        },
        {
            id: 'm62',
            name: '蒜香排骨',
            category: 'meat',
            tags: ['炸', '猪肉'],
            ingredients: ['排骨', '蒜', '生抽', '料酒', '淀粉'],
            time: '40分钟',
            difficulty: '中等',
            method: '排骨用蒜蓉腌制，裹粉炸至金黄',
            note: '蒜香浓郁',
            forbidden: ['排骨汤']
        },
        {
            id: 'm63',
            name: '豉汁蒸排骨',
            category: 'meat',
            tags: ['蒸', '猪肉'],
            ingredients: ['排骨', '豆豉', '蒜', '生抽', '料酒', '淀粉'],
            time: '30分钟',
            difficulty: '简单',
            method: '排骨用豆豉蒜蓉腌制，蒸30分钟',
            note: '粤式早茶',
            forbidden: ['排骨汤']
        },
        {
            id: 'm64',
            name: '蜜汁叉烧',
            category: 'meat',
            tags: ['烤', '猪肉', '粤式'],
            ingredients: ['梅花肉', '叉烧酱', '蜂蜜', '生抽', '料酒'],
            time: '120分钟',
            difficulty: '中等',
            method: '肉用叉烧酱腌制过夜，烤箱烤制，刷蜂蜜水',
            note: '港式经典',
            forbidden: []
        },
        {
            id: 'm65',
            name: '脆皮烧肉',
            category: 'meat',
            tags: ['烤', '猪肉', '粤式'],
            ingredients: ['五花肉', '五香粉', '盐', '白醋'],
            time: '180分钟',
            difficulty: '困难',
            method: '五花肉腌制，烤至皮脆肉嫩',
            note: '需要烤箱',
            forbidden: []
        },
        {
            id: 'm66',
            name: '咕噜肉',
            category: 'meat',
            tags: ['炸', '猪肉', '糖醋'],
            ingredients: ['五花肉', '菠萝', '青椒', '糖', '醋', '番茄酱'],
            time: '40分钟',
            difficulty: '中等',
            method: '肉切丁炸酥，配菠萝青椒，淋糖醋汁',
            note: '酸甜开胃',
            forbidden: ['糖醋里脊']
        },
        {
            id: 'm67',
            name: '陈皮骨',
            category: 'meat',
            tags: ['炸', '猪肉'],
            ingredients: ['排骨', '陈皮', '生抽', '料酒', '淀粉'],
            time: '40分钟',
            difficulty: '中等',
            method: '排骨用陈皮腌制，裹粉炸至金黄',
            note: '陈皮清香',
            forbidden: ['排骨汤']
        },
        {
            id: 'm68',
            name: '橙汁排骨',
            category: 'meat',
            tags: ['炖', '猪肉', '甜'],
            ingredients: ['排骨', '橙汁', '糖', '生抽', '醋'],
            time: '50分钟',
            difficulty: '中等',
            method: '排骨煎至金黄，加橙汁和调料炖30分钟',
            note: '果香四溢',
            forbidden: ['排骨汤']
        },
        {
            id: 'm69',
            name: '可乐猪蹄',
            category: 'meat',
            tags: ['炖', '猪肉'],
            ingredients: ['猪蹄', '可乐', '生抽', '老抽', '姜'],
            time: '90分钟',
            difficulty: '中等',
            method: '猪蹄焯水，加可乐和调料炖1小时',
            note: '软糯入味',
            forbidden: ['各种荤汤']
        },
        {
            id: 'm70',
            name: '红烧猪蹄',
            category: 'meat',
            tags: ['炖', '猪肉'],
            ingredients: ['猪蹄', '生抽', '老抽', '冰糖', '八角', '桂皮'],
            time: '120分钟',
            difficulty: '中等',
            method: '猪蹄焯水炒糖色，加调料炖2小时',
            note: '胶原蛋白满满',
            forbidden: ['各种荤汤']
        },
        {
            id: 'm71',
            name: '脆皮五花肉',
            category: 'meat',
            tags: ['烤', '猪肉'],
            ingredients: ['五花肉', '盐', '五香粉', '白醋'],
            time: '90分钟',
            difficulty: '中等',
            method: '五花肉腌制，高温烤至皮脆',
            note: '网红做法',
            forbidden: []
        },
        {
            id: 'm72',
            name: '蒜泥茄子肉末',
            category: 'meat',
            tags: ['炒', '猪肉'],
            ingredients: ['茄子', '肉末', '蒜', '生抽', '豆瓣酱'],
            time: '25分钟',
            difficulty: '简单',
            method: '茄子切条蒸熟，肉末炒熟，加蒜泥调味',
            note: '下饭好菜',
            forbidden: ['地三鲜']
        },
        {
            id: 'm73',
            name: '干煸肥肠',
            category: 'meat',
            tags: ['炒', '辣'],
            ingredients: ['肥肠', '干辣椒', '花椒', '青椒', '蒜'],
            time: '40分钟',
            difficulty: '困难',
            method: '肥肠煮熟切条，干煸至干香，加辣椒花椒',
            note: '麻辣干香',
            forbidden: ['干锅']
        },
        {
            id: 'm74',
            name: '爆炒腰花',
            category: 'meat',
            tags: ['炒', '快手'],
            ingredients: ['猪腰', '青椒', '洋葱', '姜', '料酒', '生抽'],
            time: '15分钟',
            difficulty: '困难',
            method: '腰花切花刀，大火爆炒，调味出锅',
            note: '火候关键',
            forbidden: []
        },
        {
            id: 'm75',
            name: '猪肝菠菜',
            category: 'meat',
            tags: ['炒', '营养'],
            ingredients: ['猪肝', '菠菜', '姜', '料酒', '生抽'],
            time: '15分钟',
            difficulty: '简单',
            method: '猪肝切片腌制，快炒，加菠菜',
            note: '补铁组合',
            forbidden: []
        },
        {
            id: 'm76',
            name: '花生猪脚',
            category: 'meat',
            tags: ['炖', '猪肉'],
            ingredients: ['猪蹄', '花生', '生抽', '老抽', '冰糖'],
            time: '120分钟',
            difficulty: '中等',
            method: '猪蹄花生一起炖煮2小时',
            note: '滋补养颜',
            forbidden: ['各种荤汤']
        },
        {
            id: 'm77',
            name: '黄豆焖猪蹄',
            category: 'meat',
            tags: ['炖', '猪肉'],
            ingredients: ['猪蹄', '黄豆', '生抽', '老抽', '冰糖'],
            time: '120分钟',
            difficulty: '中等',
            method: '黄豆泡发，与猪蹄一起炖煮',
            note: '软糯香浓',
            forbidden: ['各种荤汤']
        },
        {
            id: 'm78',
            name: '酸菜白肉',
            category: 'meat',
            tags: ['炖', '猪肉', '东北菜'],
            ingredients: ['五花肉', '酸菜', '粉条', '姜', '葱'],
            time: '60分钟',
            difficulty: '简单',
            method: '五花肉煮熟切片，与酸菜粉条一起炖煮',
            note: '东北经典',
            forbidden: []
        },
        {
            id: 'm79',
            name: '溜肉段',
            category: 'meat',
            tags: ['炸', '猪肉', '东北菜'],
            ingredients: ['里脊肉', '青椒', '淀粉', '生抽', '料酒'],
            time: '30分钟',
            difficulty: '中等',
            method: '肉切丁炸酥，配青椒，溜汁',
            note: '东北名菜',
            forbidden: []
        },
        {
            id: 'm80',
            name: '锅塌里脊',
            category: 'meat',
            tags: ['煎', '猪肉'],
            ingredients: ['里脊肉', '鸡蛋', '葱', '姜', '生抽'],
            time: '25分钟',
            difficulty: '中等',
            method: '里脊片腌制，裹蛋液煎制，加调味汁',
            note: '软嫩鲜香',
            forbidden: []
        },
        {
            id: 'm81',
            name: '牙签肉',
            category: 'meat',
            tags: ['炸', '猪肉', '小吃'],
            ingredients: ['里脊肉', '孜然', '辣椒面', '芝麻', '料酒'],
            time: '30分钟',
            difficulty: '简单',
            method: '肉切丁用牙签串起，炸至金黄，撒调料',
            note: '下酒好菜',
            forbidden: []
        },
        {
            id: 'm82',
            name: '炸酥肉',
            category: 'meat',
            tags: ['炸', '猪肉', '小吃'],
            ingredients: ['五花肉', '花椒粉', '生抽', '料酒', '淀粉'],
            time: '30分钟',
            difficulty: '简单',
            method: '肉条腌制，裹糊炸至金黄酥脆',
            note: '香酥可口',
            forbidden: []
        },
        {
            id: 'm83',
            name: '小酥肉',
            category: 'meat',
            tags: ['炸', '猪肉'],
            ingredients: ['五花肉', '鸡蛋', '淀粉', '花椒粉', '生抽'],
            time: '30分钟',
            difficulty: '简单',
            method: '肉条腌制，裹蛋糊炸至金黄',
            note: '火锅必备',
            forbidden: []
        },
        {
            id: 'm84',
            name: '软炸里脊',
            category: 'meat',
            tags: ['炸', '猪肉'],
            ingredients: ['里脊肉', '鸡蛋', '淀粉', '盐'],
            time: '25分钟',
            difficulty: '简单',
            method: '里脊切条，裹软炸糊，温油炸至浅黄',
            note: '外软里嫩',
            forbidden: []
        },
        {
            id: 'm85',
            name: '干炸丸子',
            category: 'meat',
            tags: ['炸', '猪肉'],
            ingredients: ['猪肉馅', '鸡蛋', '淀粉', '葱', '姜', '生抽'],
            time: '30分钟',
            difficulty: '中等',
            method: '肉馅调味搅打上劲，挤丸子炸至金黄',
            note: '外酥里嫩',
            forbidden: ['红烧狮子头']
        },
        {
            id: 'm86',
            name: '四喜丸子',
            category: 'meat',
            tags: ['炖', '猪肉', '宴席'],
            ingredients: ['猪肉馅', '鸡蛋', '淀粉', '生抽', '老抽', '葱', '姜'],
            time: '60分钟',
            difficulty: '中等',
            method: '肉馅做大丸子，煎至定型，加调料炖30分钟',
            note: '宴席大菜',
            forbidden: ['红烧狮子头']
        },
        {
            id: 'm87',
            name: '珍珠丸子',
            category: 'meat',
            tags: ['蒸', '猪肉'],
            ingredients: ['猪肉馅', '糯米', '生抽', '料酒', '葱', '姜'],
            time: '40分钟',
            difficulty: '简单',
            method: '肉馅调味，裹泡好的糯米，蒸30分钟',
            note: '晶莹剔透',
            forbidden: []
        },
        {
            id: 'm88',
            name: '酿豆腐',
            category: 'meat',
            tags: ['酿', '猪肉'],
            ingredients: ['豆腐', '猪肉馅', '生抽', '葱', '淀粉'],
            time: '30分钟',
            difficulty: '中等',
            method: '豆腐切块挖空，填入肉馅，煎至金黄，加调味汁',
            note: '客家名菜',
            forbidden: []
        },
        {
            id: 'm89',
            name: '酿茄子',
            category: 'meat',
            tags: ['酿', '猪肉'],
            ingredients: ['茄子', '猪肉馅', '生抽', '葱', '淀粉'],
            time: '30分钟',
            difficulty: '中等',
            method: '茄子切段挖空，填入肉馅，煎至金黄',
            note: '下饭好菜',
            forbidden: ['地三鲜']
        },
        {
            id: 'm90',
            name: '酿苦瓜',
            category: 'meat',
            tags: ['酿', '猪肉'],
            ingredients: ['苦瓜', '猪肉馅', '生抽', '葱', '淀粉'],
            time: '30分钟',
            difficulty: '中等',
            method: '苦瓜切段去瓤，填入肉馅，煎至金黄',
            note: '苦中带香',
            forbidden: []
        },
        {
            id: 'm91',
            name: '冬瓜盅',
            category: 'meat',
            tags: ['蒸', '猪肉'],
            ingredients: ['小冬瓜', '猪肉馅', '虾仁', '香菇', '生抽'],
            time: '60分钟',
            difficulty: '困难',
            method: '冬瓜挖空，填入肉馅配料，蒸1小时',
            note: '造型精美',
            forbidden: []
        },
        {
            id: 'm92',
            name: '荷叶粉蒸肉',
            category: 'meat',
            tags: ['蒸', '猪肉'],
            ingredients: ['五花肉', '蒸肉米粉', '荷叶', '生抽', '料酒'],
            time: '90分钟',
            difficulty: '中等',
            method: '五花肉腌制，裹米粉，包荷叶蒸1.5小时',
            note: '荷叶清香',
            forbidden: []
        },
        {
            id: 'm93',
            name: '腊味合蒸',
            category: 'meat',
            tags: ['蒸', '腊味'],
            ingredients: ['腊肉', '腊肠', '腊鱼', '姜', '料酒'],
            time: '40分钟',
            difficulty: '简单',
            method: '腊味切片摆盘，蒸40分钟',
            note: '湘菜经典',
            forbidden: ['各种荤汤']
        },
        {
            id: 'm94',
            name: '培根金针菇卷',
            category: 'meat',
            tags: ['烤', '西式'],
            ingredients: ['培根', '金针菇', '黑胡椒', '生抽'],
            time: '20分钟',
            difficulty: '简单',
            method: '金针菇用培根卷起，煎或烤至金黄',
            note: '鲜香美味',
            forbidden: []
        },
        {
            id: 'm95',
            name: '培根芦笋卷',
            category: 'meat',
            tags: ['烤', '西式'],
            ingredients: ['培根', '芦笋', '黑胡椒'],
            time: '15分钟',
            difficulty: '简单',
            method: '芦笋用培根卷起，煎或烤至金黄',
            note: '健康美味',
            forbidden: []
        },
        {
            id: 'm96',
            name: '芝士焗虾',
            category: 'meat',
            tags: ['烤', '海鲜', '西式'],
            ingredients: ['虾', '芝士', '黄油', '蒜', '黑胡椒'],
            time: '20分钟',
            difficulty: '简单',
            method: '虾开背去虾线，撒蒜蓉黄油，铺芝士烤至融化',
            note: '奶香浓郁',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 'm97',
            name: '黄油焗龙虾',
            category: 'meat',
            tags: ['烤', '海鲜', '西式'],
            ingredients: ['龙虾', '黄油', '蒜', '柠檬', '欧芹'],
            time: '30分钟',
            difficulty: '中等',
            method: '龙虾对半切开，涂黄油蒜蓉，烤15分钟',
            note: '高端大气',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 'm98',
            name: '铁板鱿鱼',
            category: 'meat',
            tags: ['铁板', '海鲜'],
            ingredients: ['鱿鱼', '洋葱', '青椒', '孜然', '辣椒面'],
            time: '15分钟',
            difficulty: '简单',
            method: '鱿鱼切花刀，铁板煎制，撒孜然辣椒',
            note: '街边美味',
            forbidden: []
        },
        {
            id: 'm99',
            name: '铁板牛肉',
            category: 'meat',
            tags: ['铁板', '牛肉'],
            ingredients: ['牛肉', '洋葱', '黑胡椒', '生抽', '黄油'],
            time: '15分钟',
            difficulty: '简单',
            method: '牛肉切片腌制，铁板煎制，配洋葱',
            note: '滋滋作响',
            forbidden: []
        },
        {
            id: 'm100',
            name: '石锅拌饭',
            category: 'meat',
            tags: ['拌', '牛肉', '韩式'],
            ingredients: ['米饭', '牛肉', '菠菜', '豆芽', '胡萝卜', '鸡蛋', '韩式辣酱'],
            time: '30分钟',
            difficulty: '中等',
            method: '配菜分别炒熟，牛肉炒熟，石锅铺米饭摆菜，加蛋和辣酱',
            note: '韩式经典',
            forbidden: []
        }
    ],
    
    // 汤类
    soup: [
        {
            id: 's1',
            name: '番茄蛋花汤',
            category: 'soup',
            tags: ['快手', '清淡', '汤'],
            ingredients: ['西红柿', '鸡蛋', '葱', '盐', '香油'],
            time: '10分钟',
            difficulty: '简单',
            method: '西红柿切块炒出汁，加水烧开，淋入打散的鸡蛋，调味，撒葱花',
            note: '快手素汤',
            forbidden: []
        },
        {
            id: 's2',
            name: '紫菜蛋花汤',
            category: 'soup',
            tags: ['快手', '清淡', '汤'],
            ingredients: ['紫菜', '鸡蛋', '虾皮', '葱', '盐', '香油'],
            time: '5分钟',
            difficulty: '简单',
            method: '水烧开，放入紫菜和虾皮，淋入鸡蛋液，调味，撒葱花',
            note: '最简单的汤',
            forbidden: []
        },
        {
            id: 's3',
            name: '青菜豆腐汤',
            category: 'soup',
            tags: ['清淡', '素汤'],
            ingredients: ['上海青', '嫩豆腐', '姜', '盐', '香油'],
            time: '15分钟',
            difficulty: '简单',
            method: '豆腐切块，水烧开，放入豆腐和青菜，煮5分钟，调味',
            note: '清淡健康',
            forbidden: []
        },
        {
            id: 's4',
            name: '冬瓜丸子汤',
            category: 'soup',
            tags: ['清淡', '汤'],
            ingredients: ['冬瓜', '猪肉馅', '姜', '葱', '盐', '胡椒粉'],
            time: '30分钟',
            difficulty: '中等',
            method: '冬瓜切块，肉馅加调料做成丸子，水烧开，放入丸子煮熟，加冬瓜煮软，调味',
            note: '需要猪肉馅',
            forbidden: []
        },
        {
            id: 's5',
            name: '玉米排骨汤',
            category: 'soup',
            tags: ['汤', '滋补'],
            ingredients: ['玉米', '排骨', '姜', '葱', '盐'],
            time: '60分钟',
            difficulty: '中等',
            method: '排骨焯水，玉米切段，一起炖煮1小时，调味',
            note: '需要排骨',
            forbidden: []
        },
        {
            id: 's6',
            name: '丝瓜蛋汤',
            category: 'soup',
            tags: ['清淡', '快手'],
            ingredients: ['丝瓜', '鸡蛋', '盐', '香油'],
            time: '10分钟',
            difficulty: '简单',
            method: '丝瓜去皮切块，水烧开，放入丝瓜煮软，淋入蛋液，调味',
            note: '清甜爽口',
            forbidden: []
        },
        {
            id: 's7',
            name: '蘑菇蛋汤',
            category: 'soup',
            tags: ['清淡', '快手'],
            ingredients: ['口蘑', '鸡蛋', '葱', '盐', '香油'],
            time: '10分钟',
            difficulty: '简单',
            method: '口蘑切片，水烧开，放入口蘑煮5分钟，淋入蛋液，调味',
            note: '鲜美可口',
            forbidden: []
        },
        {
            id: 's8',
            name: '海带豆腐汤',
            category: 'soup',
            tags: ['清淡', '营养'],
            ingredients: ['海带', '豆腐', '姜', '盐', '香油'],
            time: '15分钟',
            difficulty: '简单',
            method: '海带泡软，豆腐切块，水烧开，放入海带豆腐煮10分钟，调味',
            note: '补钙佳品',
            forbidden: []
        },
        {
            id: 's9',
            name: '萝卜丝煎蛋汤',
            category: 'soup',
            tags: ['清淡', '快手'],
            ingredients: ['白萝卜', '鸡蛋', '葱', '盐', '白胡椒'],
            time: '15分钟',
            difficulty: '简单',
            method: '萝卜切丝，先煎鸡蛋，加水烧开，放入萝卜丝煮软，调味',
            note: '鲜美暖胃',
            forbidden: []
        },
        {
            id: 's10',
            name: '菠菜蛋汤',
            category: 'soup',
            tags: ['清淡', '快手'],
            ingredients: ['菠菜', '鸡蛋', '盐', '香油'],
            time: '10分钟',
            difficulty: '简单',
            method: '菠菜洗净，水烧开，放入菠菜煮软，淋入蛋液，调味',
            note: '补铁佳品',
            forbidden: ['菠菜豆腐汤']
        },
        {
            id: 's11',
            name: '酸辣汤',
            category: 'soup',
            tags: ['酸辣', '开胃'],
            ingredients: ['豆腐', '木耳', '香菇', '鸡蛋', '醋', '白胡椒', '淀粉'],
            time: '20分钟',
            difficulty: '简单',
            method: '豆腐木耳香菇切丝，水烧开，放入食材煮5分钟，勾芡，淋蛋液，加醋和胡椒',
            note: '开胃暖身',
            forbidden: ['西湖牛肉羹']
        },
        {
            id: 's12',
            name: '西红柿鸡蛋汤',
            category: 'soup',
            tags: ['清淡', '快手'],
            ingredients: ['西红柿', '鸡蛋', '葱', '盐', '香油'],
            time: '10分钟',
            difficulty: '简单',
            method: '西红柿切块炒出汁，加水烧开，淋入蛋液，调味',
            note: '经典家常',
            forbidden: []
        },
        {
            id: 's13',
            name: '莲藕排骨汤',
            category: 'soup',
            tags: ['滋补', '汤'],
            ingredients: ['莲藕', '排骨', '姜', '葱', '盐'],
            time: '90分钟',
            difficulty: '中等',
            method: '排骨焯水，莲藕切块，一起炖煮1.5小时，调味',
            note: '需要排骨',
            forbidden: ['藕']
        },
        {
            id: 's14',
            name: '玉米浓汤',
            category: 'soup',
            tags: ['西式', '甜汤'],
            ingredients: ['玉米', '牛奶', '黄油', '面粉', '盐'],
            time: '30分钟',
            difficulty: '中等',
            method: '玉米粒打碎，黄油炒面粉，加牛奶和玉米，煮至浓稠，调味',
            note: '西式浓汤',
            forbidden: []
        },
        {
            id: 's15',
            name: '南瓜汤',
            category: 'soup',
            tags: ['甜汤', '营养'],
            ingredients: ['南瓜', '牛奶', '黄油', '盐'],
            time: '30分钟',
            difficulty: '简单',
            method: '南瓜蒸熟，加牛奶打成泥，回锅加热，调味',
            note: '香甜浓郁',
            forbidden: []
        },
        {
            id: 's16',
            name: '银耳莲子汤',
            category: 'soup',
            tags: ['甜汤', '滋补'],
            ingredients: ['银耳', '莲子', '冰糖', '枸杞'],
            time: '60分钟',
            difficulty: '简单',
            method: '银耳莲子泡发，加水炖煮1小时，加冰糖枸杞',
            note: '美容养颜',
            forbidden: []
        },
        {
            id: 's17',
            name: '酒酿圆子',
            category: 'soup',
            tags: ['甜汤', '快手'],
            ingredients: ['汤圆', '酒酿', '冰糖', '桂花'],
            time: '15分钟',
            difficulty: '简单',
            method: '汤圆煮熟，加酒酿和冰糖，撒桂花',
            note: '冷冻汤圆可用',
            forbidden: []
        },
        {
            id: 's18',
            name: '酸辣肚丝汤',
            category: 'soup',
            tags: ['酸辣', '汤'],
            ingredients: ['猪肚', '笋丝', '木耳', '醋', '白胡椒', '淀粉'],
            time: '30分钟',
            difficulty: '中等',
            method: '猪肚切丝，炒香配料，加水煮开，勾芡，加醋和胡椒',
            note: '冷冻猪肚可用',
            forbidden: []
        },
        {
            id: 's19',
            name: '味噌汤',
            category: 'soup',
            tags: ['日式', '快手'],
            ingredients: ['味噌', '豆腐', '海带', '葱花'],
            time: '10分钟',
            difficulty: '简单',
            method: '水烧开，放入豆腐和海带，关火，加入味噌化开，撒葱花',
            note: '日式家常',
            forbidden: []
        },
        {
            id: 's20',
            name: '罗宋汤',
            category: 'soup',
            tags: ['西式', '营养'],
            ingredients: ['牛肉', '西红柿', '洋葱', '土豆', '胡萝卜', '卷心菜'],
            time: '90分钟',
            difficulty: '中等',
            method: '牛肉炖煮1小时，加蔬菜再煮30分钟，调味',
            note: '浓郁营养',
            forbidden: []
        },
        {
            id: 's21',
            name: '皮蛋瘦肉粥',
            category: 'soup',
            tags: ['粥', '早餐'],
            ingredients: ['大米', '瘦肉', '皮蛋', '姜', '葱', '盐'],
            time: '40分钟',
            difficulty: '简单',
            method: '大米煮粥，瘦肉切丝腌制，粥熟时加肉丝和皮蛋，调味撒葱',
            note: '暖胃早餐',
            forbidden: []
        },
        {
            id: 's22',
            name: '鱼片粥',
            category: 'soup',
            tags: ['粥', '海鲜'],
            ingredients: ['大米', '鱼片', '姜', '葱', '盐', '胡椒粉'],
            time: '35分钟',
            difficulty: '简单',
            method: '大米煮粥，鱼片腌制，粥熟时放入鱼片烫熟，调味',
            note: '鲜美营养',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 's23',
            name: '鸡丝粥',
            category: 'soup',
            tags: ['粥', '早餐'],
            ingredients: ['大米', '鸡胸肉', '姜', '葱', '盐'],
            time: '40分钟',
            difficulty: '简单',
            method: '大米煮粥，鸡胸肉煮熟撕丝，粥熟时加鸡丝，调味',
            note: '清淡养胃',
            forbidden: ['鸡汤']
        },
        {
            id: 's24',
            name: '红豆粥',
            category: 'soup',
            tags: ['粥', '甜'],
            ingredients: ['大米', '红豆', '冰糖'],
            time: '60分钟',
            difficulty: '简单',
            method: '红豆提前泡发，与大米一起煮粥，加冰糖',
            note: '补血养颜',
            forbidden: []
        },
        {
            id: 's25',
            name: '绿豆粥',
            category: 'soup',
            tags: ['粥', '清热'],
            ingredients: ['大米', '绿豆', '冰糖'],
            time: '50分钟',
            difficulty: '简单',
            method: '绿豆提前泡发，与大米一起煮粥，加冰糖',
            note: '清热解暑',
            forbidden: []
        },
        {
            id: 's26',
            name: '八宝粥',
            category: 'soup',
            tags: ['粥', '甜', '营养'],
            ingredients: ['大米', '红豆', '绿豆', '莲子', '红枣', '桂圆', '花生', '冰糖'],
            time: '90分钟',
            difficulty: '中等',
            method: '所有豆类提前泡发，一起煮粥，加冰糖',
            note: '营养全面',
            forbidden: []
        },
        {
            id: 's27',
            name: '百合银耳羹',
            category: 'soup',
            tags: ['甜汤', '滋补'],
            ingredients: ['银耳', '百合', '冰糖', '枸杞'],
            time: '60分钟',
            difficulty: '简单',
            method: '银耳百合泡发，炖煮1小时，加冰糖枸杞',
            note: '润肺养颜',
            forbidden: []
        },
        {
            id: 's28',
            name: '绿豆汤',
            category: 'soup',
            tags: ['甜汤', '清热'],
            ingredients: ['绿豆', '冰糖'],
            time: '40分钟',
            difficulty: '简单',
            method: '绿豆泡发，煮至开花，加冰糖',
            note: '夏日解暑',
            forbidden: []
        },
        {
            id: 's29',
            name: '红豆沙',
            category: 'soup',
            tags: ['甜汤', '甜品'],
            ingredients: ['红豆', '冰糖', '陈皮'],
            time: '90分钟',
            difficulty: '中等',
            method: '红豆泡发煮至软烂，压成泥，加冰糖陈皮',
            note: '港式甜品',
            forbidden: []
        },
        {
            id: 's30',
            name: '杨枝甘露',
            category: 'soup',
            tags: ['甜汤', '港式'],
            ingredients: ['芒果', '西柚', '西米', '椰浆', '糖'],
            time: '30分钟',
            difficulty: '中等',
            method: '西米煮熟，芒果打泥，混合椰浆，加西柚粒',
            note: '港式经典',
            forbidden: []
        },
        {
            id: 's31',
            name: '双皮奶',
            category: 'soup',
            tags: ['甜品', '粤式'],
            ingredients: ['牛奶', '鸡蛋', '糖'],
            time: '30分钟',
            difficulty: '中等',
            method: '牛奶煮热，加蛋清糖搅匀，蒸15分钟',
            note: '嫩滑香甜',
            forbidden: []
        },
        {
            id: 's32',
            name: '姜撞奶',
            category: 'soup',
            tags: ['甜品', '粤式'],
            ingredients: ['牛奶', '姜汁', '糖'],
            time: '15分钟',
            difficulty: '中等',
            method: '牛奶加热冲入姜汁，静置凝固',
            note: '暖胃甜品',
            forbidden: []
        },
        {
            id: 's33',
            name: '木瓜炖雪蛤',
            category: 'soup',
            tags: ['甜汤', '滋补'],
            ingredients: ['木瓜', '雪蛤', '冰糖', '椰浆'],
            time: '60分钟',
            difficulty: '困难',
            method: '雪蛤泡发，与木瓜冰糖一起炖煮',
            note: '美容养颜',
            forbidden: []
        },
        {
            id: 's34',
            name: '花旗参乌鸡汤',
            category: 'soup',
            tags: ['滋补', '汤'],
            ingredients: ['乌鸡', '花旗参', '枸杞', '红枣', '姜'],
            time: '120分钟',
            difficulty: '中等',
            method: '乌鸡焯水，加所有材料炖煮2小时',
            note: '滋补佳品',
            forbidden: ['鸡汤', '乌鸡汤']
        },
        {
            id: 's35',
            name: '花胶鸡汤',
            category: 'soup',
            tags: ['滋补', '汤'],
            ingredients: ['花胶', '鸡肉', '枸杞', '红枣', '姜'],
            time: '180分钟',
            difficulty: '困难',
            method: '花胶泡发，与鸡肉一起炖煮3小时',
            note: '胶原蛋白',
            forbidden: ['鸡汤']
        },
        {
            id: 's36',
            name: '老火靓汤',
            category: 'soup',
            tags: ['炖汤', '粤式'],
            ingredients: ['猪骨', '淮山', '枸杞', '红枣', '姜'],
            time: '180分钟',
            difficulty: '简单',
            method: '猪骨焯水，加所有材料炖煮3小时',
            note: '粤式经典',
            forbidden: ['各种荤汤']
        },
        {
            id: 's37',
            name: '虫草花炖鸭',
            category: 'soup',
            tags: ['滋补', '汤'],
            ingredients: ['鸭肉', '虫草花', '枸杞', '姜'],
            time: '120分钟',
            difficulty: '中等',
            method: '鸭肉焯水，加虫草花炖煮2小时',
            note: '滋阴润肺',
            forbidden: ['鸭汤']
        },
        {
            id: 's38',
            name: '老鸭汤',
            category: 'soup',
            tags: ['炖汤', '家常'],
            ingredients: ['老鸭', '酸萝卜', '姜', '葱'],
            time: '120分钟',
            difficulty: '简单',
            method: '老鸭焯水，加酸萝卜炖煮2小时',
            note: '酸爽开胃',
            forbidden: ['鸭汤']
        },
        {
            id: 's39',
            name: '鸽子汤',
            category: 'soup',
            tags: ['滋补', '汤'],
            ingredients: ['鸽子', '枸杞', '红枣', '姜'],
            time: '90分钟',
            difficulty: '简单',
            method: '鸽子焯水，加材料炖煮1.5小时',
            note: '一鸽胜九鸡',
            forbidden: ['各种荤汤']
        },
        {
            id: 's40',
            name: '牛尾汤',
            category: 'soup',
            tags: ['滋补', '汤'],
            ingredients: ['牛尾', '西红柿', '洋葱', '胡萝卜', '姜'],
            time: '180分钟',
            difficulty: '中等',
            method: '牛尾焯水，加蔬菜炖煮3小时',
            note: '浓郁营养',
            forbidden: ['各种荤汤']
        },
        {
            id: 's41',
            name: '羊肉汤',
            category: 'soup',
            tags: ['炖汤', '温补'],
            ingredients: ['羊肉', '白萝卜', '枸杞', '姜', '葱'],
            time: '120分钟',
            difficulty: '中等',
            method: '羊肉焯水，加萝卜炖煮2小时',
            note: '冬日暖身',
            forbidden: ['各种荤汤']
        },
        {
            id: 's42',
            name: '鱼头豆腐汤',
            category: 'soup',
            tags: ['汤', '家常'],
            ingredients: ['鱼头', '豆腐', '姜', '葱', '料酒'],
            time: '40分钟',
            difficulty: '中等',
            method: '鱼头煎香，加开水煮白，加豆腐煮15分钟',
            note: '奶白鲜美',
            forbidden: ['鱼汤', '鲫鱼']
        },
        {
            id: 's43',
            name: '鲫鱼豆腐汤',
            category: 'soup',
            tags: ['汤', '家常'],
            ingredients: ['鲫鱼', '豆腐', '姜', '葱'],
            time: '40分钟',
            difficulty: '中等',
            method: '鲫鱼煎香，加开水煮白，加豆腐煮15分钟',
            note: '产妇下奶',
            forbidden: ['鱼汤', '鲫鱼']
        },
        {
            id: 's44',
            name: '黄骨鱼汤',
            category: 'soup',
            tags: ['汤', '鲜美'],
            ingredients: ['黄骨鱼', '豆腐', '姜', '葱'],
            time: '30分钟',
            difficulty: '中等',
            method: '黄骨鱼煎香，加开水煮15分钟，加豆腐',
            note: '鲜嫩少刺',
            forbidden: ['鱼汤']
        },
        {
            id: 's45',
            name: '生滚鱼片粥',
            category: 'soup',
            tags: ['粥', '粤式'],
            ingredients: ['大米', '鱼片', '姜丝', '葱', '生抽'],
            time: '30分钟',
            difficulty: '简单',
            method: '煮好白粥，放入腌制好的鱼片烫熟，调味',
            note: '早茶经典',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 's46',
            name: '艇仔粥',
            category: 'soup',
            tags: ['粥', '粤式'],
            ingredients: ['大米', '鱼片', '鱿鱼', '花生', '油条', '姜丝'],
            time: '40分钟',
            difficulty: '中等',
            method: '煮好白粥，加入各种配料烫熟，配油条',
            note: '广州特色',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        },
        {
            id: 's47',
            name: '及第粥',
            category: 'soup',
            tags: ['粥', '粤式'],
            ingredients: ['大米', '猪肉', '猪肝', '猪腰', '姜丝'],
            time: '40分钟',
            difficulty: '中等',
            method: '煮好白粥，加入猪杂烫熟，调味',
            note: '状元及第',
            forbidden: []
        },
        {
            id: 's48',
            name: '青菜瘦肉粥',
            category: 'soup',
            tags: ['粥', '家常'],
            ingredients: ['大米', '瘦肉', '青菜', '姜丝', '盐'],
            time: '35分钟',
            difficulty: '简单',
            method: '大米煮粥，瘦肉切丝腌制，粥熟时加肉丝和青菜',
            note: '清淡养胃',
            forbidden: []
        },
        {
            id: 's49',
            name: '窝蛋牛肉粥',
            category: 'soup',
            tags: ['粥', '粤式'],
            ingredients: ['大米', '牛肉', '鸡蛋', '姜丝', '葱'],
            time: '40分钟',
            difficulty: '中等',
            method: '煮好白粥，牛肉片烫熟，打入生鸡蛋搅匀',
            note: '嫩滑鲜美',
            forbidden: []
        },
        {
            id: 's50',
            name: '海鲜粥',
            category: 'soup',
            tags: ['粥', '海鲜'],
            ingredients: ['大米', '虾', '蟹', '鱿鱼', '姜丝', '葱'],
            time: '45分钟',
            difficulty: '中等',
            method: '大米煮粥，加入各种海鲜烫熟，调味',
            note: '鲜美无比',
            forbidden: ['带鱼', '鲫鱼', '鱼汤']
        }
    ],

    // 素菜
    veg: [
        {
            id: 'v1',
            name: '清炒上海青',
            category: 'veg',
            tags: ['快手', '炒', '绿叶菜'],
            ingredients: ['上海青', '蒜', '盐', '油'],
            time: '5分钟',
            difficulty: '简单',
            method: '上海青洗净，蒜爆香，大火快炒，调味出锅',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v2',
            name: '清炒西葫芦',
            category: 'veg',
            tags: ['快手', '炒'],
            ingredients: ['西葫芦', '蒜', '盐', '油'],
            time: '8分钟',
            difficulty: '简单',
            method: '西葫芦切片，蒜爆香，中火炒软，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v3',
            name: '西葫芦炒蛋',
            category: 'veg',
            tags: ['快手', '炒', '蛋'],
            ingredients: ['西葫芦', '鸡蛋', '葱', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '西葫芦切片，鸡蛋炒熟盛出，炒西葫芦，回锅鸡蛋，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v4',
            name: '蒜苔炒口蘑',
            category: 'veg',
            tags: ['炒', '菌菇'],
            ingredients: ['蒜苔', '口蘑', '蒜', '生抽', '盐'],
            time: '12分钟',
            difficulty: '简单',
            method: '蒜苔切段，口蘑切片，蒜爆香，先炒蒜苔，再下口蘑，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v5',
            name: '口蘑炒上海青',
            category: 'veg',
            tags: ['炒', '菌菇', '绿叶菜'],
            ingredients: ['口蘑', '上海青', '蒜', '盐'],
            time: '8分钟',
            difficulty: '简单',
            method: '口蘑切片，上海青洗净，蒜爆香，先炒口蘑，再下青菜，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v6',
            name: '蟹味菇炒蛋',
            category: 'veg',
            tags: ['炒', '菌菇', '蛋'],
            ingredients: ['蟹味菇', '鸡蛋', '葱', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '蟹味菇洗净，鸡蛋炒熟盛出，炒蟹味菇出水，回锅鸡蛋，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v7',
            name: '清炒芦笋',
            category: 'veg',
            tags: ['快手', '炒'],
            ingredients: ['芦笋', '蒜', '盐', '黑胡椒'],
            time: '8分钟',
            difficulty: '简单',
            method: '芦笋切段，蒜爆香，中火炒3-4分钟，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v8',
            name: '芦笋炒口蘑',
            category: 'veg',
            tags: ['炒', '菌菇'],
            ingredients: ['芦笋', '口蘑', '蒜', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '芦笋切段，口蘑切片，蒜爆香，同炒，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v9',
            name: '白菜炖豆腐',
            category: 'veg',
            tags: ['炖', '清淡'],
            ingredients: ['白菜', '豆腐', '姜', '盐', '生抽'],
            time: '20分钟',
            difficulty: '简单',
            method: '白菜切块，豆腐切块，姜爆香，炒白菜，加水和豆腐，炖煮15分钟',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v10',
            name: '清炒白菜',
            category: 'veg',
            tags: ['快手', '炒'],
            ingredients: ['白菜', '蒜', '盐', '油'],
            time: '8分钟',
            difficulty: '简单',
            method: '白菜切块，蒜爆香，大火快炒，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v11',
            name: '蒜苔炒蟹味菇',
            category: 'veg',
            tags: ['炒', '菌菇'],
            ingredients: ['蒜苔', '蟹味菇', '蒜', '生抽'],
            time: '12分钟',
            difficulty: '简单',
            method: '蒜苔切段，蟹味菇洗净，蒜爆香，同炒，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v12',
            name: '蒜苔炒蛋',
            category: 'veg',
            tags: ['炒', '蛋'],
            ingredients: ['蒜苔', '鸡蛋', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '蒜苔切段，鸡蛋炒熟盛出，炒蒜苔，回锅鸡蛋，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v13',
            name: '青椒炒蛋',
            category: 'veg',
            tags: ['快手', '炒', '蛋'],
            ingredients: ['青椒', '鸡蛋', '葱', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '青椒切丝，鸡蛋炒熟盛出，炒青椒，回锅鸡蛋，调味',
            note: '可用现有食材',
            forbidden: []
        },
        {
            id: 'v14',
            name: '蒜蓉西兰花',
            category: 'veg',
            tags: ['快手', '炒', '健康'],
            ingredients: ['西兰花', '蒜', '盐', '油'],
            time: '8分钟',
            difficulty: '简单',
            method: '西兰花掰小朵焯水，蒜爆香，大火快炒，调味',
            note: '营养健康',
            forbidden: []
        },
        {
            id: 'v15',
            name: '蚝油生菜',
            category: 'veg',
            tags: ['快手', '炒'],
            ingredients: ['生菜', '蒜', '蚝油', '生抽'],
            time: '5分钟',
            difficulty: '简单',
            method: '生菜洗净，蒜爆香，大火快炒，淋蚝油',
            note: '清脆爽口',
            forbidden: []
        },
        {
            id: 'v16',
            name: '干煸豆角',
            category: 'veg',
            tags: ['炒', '干煸'],
            ingredients: ['四季豆', '干辣椒', '花椒', '蒜', '生抽'],
            time: '15分钟',
            difficulty: '中等',
            method: '豆角切段，干煸至虎皮状，加辣椒花椒蒜炒香，调味',
            note: '干香下饭',
            forbidden: ['干锅']
        },
        {
            id: 'v17',
            name: '麻婆豆腐',
            category: 'veg',
            tags: ['烧', '辣', '经典'],
            ingredients: ['嫩豆腐', '豆瓣酱', '花椒粉', '葱', '姜', '蒜'],
            time: '20分钟',
            difficulty: '中等',
            method: '豆腐切块焯水，炒香豆瓣酱，加水煮开，放入豆腐，勾芡撒花椒粉',
            note: '麻辣鲜香',
            forbidden: []
        },
        {
            id: 'v18',
            name: '家常豆腐',
            category: 'veg',
            tags: ['烧', '香'],
            ingredients: ['豆腐', '木耳', '胡萝卜', '生抽', '糖', '葱'],
            time: '20分钟',
            difficulty: '简单',
            method: '豆腐切块煎至金黄，加配菜和调料，烧入味',
            note: '香嫩可口',
            forbidden: []
        },
        {
            id: 'v19',
            name: '红烧茄子',
            category: 'veg',
            tags: ['烧', '下饭'],
            ingredients: ['茄子', '蒜', '生抽', '糖', '醋', '淀粉'],
            time: '20分钟',
            difficulty: '中等',
            method: '茄子切条用盐杀水，少油煎软，加调味汁烧入味',
            note: '少油版',
            forbidden: ['地三鲜']
        },
        {
            id: 'v20',
            name: '虎皮青椒',
            category: 'veg',
            tags: ['煎', '辣'],
            ingredients: ['青椒', '蒜', '生抽', '醋', '糖'],
            time: '15分钟',
            difficulty: '简单',
            method: '青椒整根干煎至虎皮，加调味汁焖入味',
            note: '酸辣开胃',
            forbidden: []
        },
        {
            id: 'v21',
            name: '糖醋藕片',
            category: 'veg',
            tags: ['炒', '糖醋'],
            ingredients: ['藕', '糖', '醋', '生抽', '淀粉'],
            time: '15分钟',
            difficulty: '简单',
            method: '藕切片，焯水，加糖醋汁炒匀',
            note: '酸甜脆爽',
            forbidden: ['藕']
        },
        {
            id: 'v22',
            name: '荷塘月色',
            category: 'veg',
            tags: ['炒', '清爽'],
            ingredients: ['藕', '木耳', '荷兰豆', '胡萝卜', '盐'],
            time: '15分钟',
            difficulty: '简单',
            method: '所有食材切片焯水，大火快炒，调味',
            note: '色彩丰富',
            forbidden: ['藕', '荷兰豆']
        },
        {
            id: 'v23',
            name: '凉拌木耳',
            category: 'veg',
            tags: ['凉拌', '快手'],
            ingredients: ['木耳', '蒜', '生抽', '醋', '香油', '辣椒油'],
            time: '15分钟',
            difficulty: '简单',
            method: '木耳泡发焯水，加所有调料拌匀',
            note: '爽口开胃',
            forbidden: ['凉拌黄瓜', '凉拌腐竹']
        },
        {
            id: 'v24',
            name: '凉拌海带丝',
            category: 'veg',
            tags: ['凉拌', '快手'],
            ingredients: ['海带', '蒜', '生抽', '醋', '香油', '辣椒油'],
            time: '15分钟',
            difficulty: '简单',
            method: '海带泡软切丝焯水，加调料拌匀',
            note: '清爽下饭',
            forbidden: ['凉拌黄瓜']
        },
        {
            id: 'v25',
            name: '拍黄瓜',
            category: 'veg',
            tags: ['凉拌', '快手'],
            ingredients: ['黄瓜', '蒜', '生抽', '醋', '香油'],
            time: '5分钟',
            difficulty: '简单',
            method: '黄瓜拍碎切段，加调料拌匀',
            note: '夏日必备',
            forbidden: ['凉拌黄瓜']
        },
        {
            id: 'v26',
            name: '糖拌西红柿',
            category: 'veg',
            tags: ['凉拌', '甜'],
            ingredients: ['西红柿', '糖'],
            time: '5分钟',
            difficulty: '简单',
            method: '西红柿切片，撒糖，腌制10分钟',
            note: '清甜爽口',
            forbidden: []
        },
        {
            id: 'v27',
            name: '松仁玉米',
            category: 'veg',
            tags: ['炒', '甜'],
            ingredients: ['玉米粒', '松仁', '胡萝卜', '盐', '糖'],
            time: '10分钟',
            difficulty: '简单',
            method: '玉米粒胡萝卜丁炒熟，加松仁，调味',
            note: '香甜可口',
            forbidden: []
        },
        {
            id: 'v28',
            name: '玉米炒蛋',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['玉米粒', '鸡蛋', '葱', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '鸡蛋炒熟盛出，炒玉米粒，回锅鸡蛋，调味',
            note: '简单美味',
            forbidden: []
        },
        {
            id: 'v29',
            name: '拔丝地瓜',
            category: 'veg',
            tags: ['炸', '甜'],
            ingredients: ['红薯', '糖', '油'],
            time: '30分钟',
            difficulty: '中等',
            method: '红薯切块炸熟，炒糖至金黄，倒入红薯拌匀',
            note: '甜蜜诱人',
            forbidden: []
        },
        {
            id: 'v30',
            name: '蒸南瓜',
            category: 'veg',
            tags: ['蒸', '甜'],
            ingredients: ['南瓜', '红枣', '枸杞'],
            time: '20分钟',
            difficulty: '简单',
            method: '南瓜切块摆盘，蒸20分钟，撒红枣枸杞',
            note: '香甜软糯',
            forbidden: []
        },
        {
            id: 'v31',
            name: '蒜蓉蒸茄子',
            category: 'veg',
            tags: ['蒸', '香'],
            ingredients: ['茄子', '蒜', '生抽', '香油', '葱'],
            time: '20分钟',
            difficulty: '简单',
            method: '茄子切条蒸15分钟，淋蒜蓉生抽香油',
            note: '少油健康',
            forbidden: ['地三鲜']
        },
        {
            id: 'v32',
            name: '烤红薯',
            category: 'veg',
            tags: ['烤', '甜'],
            ingredients: ['红薯'],
            time: '60分钟',
            difficulty: '简单',
            method: '红薯洗净，烤箱200度烤1小时',
            note: '冬日必备',
            forbidden: []
        },
        {
            id: 'v33',
            name: '炒土豆丝',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['土豆', '醋', '辣椒', '蒜', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '土豆切丝泡水，大火快炒，加醋调味',
            note: '酸辣爽口',
            forbidden: []
        },
        {
            id: 'v34',
            name: '土豆泥',
            category: 'veg',
            tags: ['煮', '西式'],
            ingredients: ['土豆', '牛奶', '黄油', '盐', '黑胡椒'],
            time: '30分钟',
            difficulty: '简单',
            method: '土豆煮熟压泥，加牛奶黄油拌匀，调味',
            note: '细腻香滑',
            forbidden: []
        },
        {
            id: 'v35',
            name: '地三鲜',
            category: 'veg',
            tags: ['炒', '东北菜'],
            ingredients: ['茄子', '土豆', '青椒', '生抽', '糖', '淀粉'],
            time: '25分钟',
            difficulty: '中等',
            method: '三种食材分别过油，回锅加调味汁炒匀',
            note: '经典东北菜',
            forbidden: ['地三鲜']
        },
        {
            id: 'v36',
            name: '香菇菜心',
            category: 'veg',
            tags: ['炒', '清爽'],
            ingredients: ['菜心', '香菇', '蒜', '生抽', '蚝油'],
            time: '15分钟',
            difficulty: '简单',
            method: '菜心焯水，香菇切片炒香，加菜心炒匀，调味',
            note: '清淡鲜美',
            forbidden: []
        },
        {
            id: 'v37',
            name: '莴笋炒蛋',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['莴笋', '鸡蛋', '蒜', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '莴笋切片，鸡蛋炒熟盛出，炒莴笋，回锅鸡蛋，调味',
            note: '清脆可口',
            forbidden: []
        },
        {
            id: 'v38',
            name: '芹菜炒香干',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['芹菜', '香干', '蒜', '生抽', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '芹菜切段，香干切片，大火快炒，调味',
            note: '清爽下饭',
            forbidden: ['凉拌腐竹']
        },
        {
            id: 'v39',
            name: '毛豆炒蛋',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['毛豆', '鸡蛋', '盐'],
            time: '15分钟',
            difficulty: '简单',
            method: '毛豆煮熟，鸡蛋炒熟，回锅毛豆，调味',
            note: '营养均衡',
            forbidden: []
        },
        {
            id: 'v40',
            name: '葱油拌面',
            category: 'veg',
            tags: ['拌', '快手'],
            ingredients: ['面条', '葱', '生抽', '糖', '油'],
            time: '15分钟',
            difficulty: '简单',
            method: '炸香葱油，煮面，淋葱油拌匀',
            note: '上海特色',
            forbidden: []
        },
        {
            id: 'v41',
            name: '蛋炒饭',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['米饭', '鸡蛋', '葱', '盐', '生抽'],
            time: '10分钟',
            difficulty: '简单',
            method: '鸡蛋炒熟，加米饭炒散，加生抽调味，撒葱花',
            note: '剩饭好去处',
            forbidden: []
        },
        {
            id: 'v42',
            name: '酱油炒饭',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['米饭', '鸡蛋', '生抽', '老抽', '葱'],
            time: '10分钟',
            difficulty: '简单',
            method: '鸡蛋炒熟，加米饭，加酱油炒匀，撒葱花',
            note: '色泽诱人',
            forbidden: []
        },
        {
            id: 'v43',
            name: '扬州炒饭',
            category: 'veg',
            tags: ['炒', '经典'],
            ingredients: ['米饭', '鸡蛋', '胡萝卜', '青豆', '玉米', '火腿'],
            time: '15分钟',
            difficulty: '中等',
            method: '所有配料切丁炒熟，加米饭炒匀，调味',
            note: '配料丰富',
            forbidden: []
        },
        {
            id: 'v44',
            name: '小米粥',
            category: 'veg',
            tags: ['煮', '早餐'],
            ingredients: ['小米', '水'],
            time: '30分钟',
            difficulty: '简单',
            method: '小米洗净，加水煮至浓稠',
            note: '养胃早餐',
            forbidden: []
        },
        {
            id: 'v45',
            name: '皮蛋瘦肉粥',
            category: 'veg',
            tags: ['煮', '早餐'],
            ingredients: ['大米', '皮蛋', '瘦肉丝', '姜', '葱'],
            time: '40分钟',
            difficulty: '中等',
            method: '大米煮粥，加入肉丝和皮蛋，调味撒葱花',
            note: '经典早餐',
            forbidden: []
        },
        {
            id: 'v46',
            name: '南瓜粥',
            category: 'veg',
            tags: ['煮', '甜'],
            ingredients: ['大米', '南瓜', '冰糖'],
            time: '40分钟',
            difficulty: '简单',
            method: '南瓜切块和大米一起煮，煮至软烂',
            note: '香甜暖胃',
            forbidden: []
        },
        {
            id: 'v47',
            name: '蒸蛋',
            category: 'veg',
            tags: ['蒸', '快手'],
            ingredients: ['鸡蛋', '温水', '盐', '生抽'],
            time: '15分钟',
            difficulty: '简单',
            method: '鸡蛋打散加温水，蒸12分钟，淋生抽',
            note: '嫩滑可口',
            forbidden: []
        },
        {
            id: 'v48',
            name: '卤蛋',
            category: 'veg',
            tags: ['卤', '小菜'],
            ingredients: ['鸡蛋', '生抽', '老抽', '八角', '桂皮'],
            time: '40分钟',
            difficulty: '简单',
            method: '鸡蛋煮熟剥壳，加调料水煮30分钟，浸泡过夜',
            note: '提前准备',
            forbidden: []
        },
        {
            id: 'v49',
            name: '茶叶蛋',
            category: 'veg',
            tags: ['卤', '小吃'],
            ingredients: ['鸡蛋', '茶叶', '生抽', '老抽', '八角', '桂皮'],
            time: '60分钟',
            difficulty: '简单',
            method: '鸡蛋煮熟敲裂，加所有调料水煮1小时，浸泡过夜',
            note: '香气浓郁',
            forbidden: []
        },
        {
            id: 'v50',
            name: '白灼菜心',
            category: 'veg',
            tags: ['煮', '清淡'],
            ingredients: ['菜心', '生抽', '蚝油', '蒜'],
            time: '5分钟',
            difficulty: '简单',
            method: '菜心焯水，摆盘，淋生抽蚝油蒜蓉',
            note: '粤菜经典',
            forbidden: []
        },
        {
            id: 'v51',
            name: '上汤娃娃菜',
            category: 'veg',
            tags: ['煮', '清淡'],
            ingredients: ['娃娃菜', '皮蛋', '火腿', '蒜', '盐'],
            time: '15分钟',
            difficulty: '简单',
            method: '娃娃菜切开，用高汤煮熟，加皮蛋火腿',
            note: '鲜美清甜',
            forbidden: ['各种荤汤']
        },
        {
            id: 'v52',
            name: '干锅花菜',
            category: 'veg',
            tags: ['炒', '干锅'],
            ingredients: ['花菜', '五花肉', '干辣椒', '蒜', '生抽'],
            time: '15分钟',
            difficulty: '简单',
            method: '花菜焯水，干煸至微焦，加配料炒香',
            note: '干香下饭',
            forbidden: ['干锅']
        },
        {
            id: 'v53',
            name: '干锅土豆片',
            category: 'veg',
            tags: ['炒', '干锅'],
            ingredients: ['土豆', '五花肉', '干辣椒', '蒜', '生抽'],
            time: '20分钟',
            difficulty: '简单',
            method: '土豆切片煎至金黄，加配料炒香',
            note: '外酥里糯',
            forbidden: ['干锅']
        },
        {
            id: 'v54',
            name: '醋溜白菜',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['白菜', '醋', '生抽', '蒜', '干辣椒'],
            time: '8分钟',
            difficulty: '简单',
            method: '白菜切片，大火快炒，加醋调味',
            note: '酸爽开胃',
            forbidden: []
        },
        {
            id: 'v55',
            name: '醋溜土豆丝',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['土豆', '醋', '干辣椒', '蒜'],
            time: '8分钟',
            difficulty: '简单',
            method: '土豆丝泡水去淀粉，大火快炒，加醋',
            note: '爽脆可口',
            forbidden: []
        },
        {
            id: 'v56',
            name: '清炒油麦菜',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['油麦菜', '蒜', '盐'],
            time: '5分钟',
            difficulty: '简单',
            method: '油麦菜洗净，蒜爆香，大火快炒',
            note: '清香脆嫩',
            forbidden: []
        },
        {
            id: 'v57',
            name: '清炒芥蓝',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['芥蓝', '蒜', '盐', '糖'],
            time: '5分钟',
            difficulty: '简单',
            method: '芥蓝焯水，蒜爆香，大火快炒',
            note: '清脆爽口',
            forbidden: []
        },
        {
            id: 'v58',
            name: '蒜蓉空心菜',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['空心菜', '蒜', '盐'],
            time: '5分钟',
            difficulty: '简单',
            method: '空心菜洗净，蒜爆香，大火快炒',
            note: '夏日时令',
            forbidden: []
        },
        {
            id: 'v59',
            name: '蒜蓉苋菜',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['苋菜', '蒜', '盐'],
            time: '5分钟',
            difficulty: '简单',
            method: '苋菜洗净，蒜爆香，大火快炒',
            note: '补血养颜',
            forbidden: []
        },
        {
            id: 'v60',
            name: '蒜蓉番薯叶',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['番薯叶', '蒜', '盐'],
            time: '5分钟',
            difficulty: '简单',
            method: '番薯叶摘嫩叶，蒜爆香，大火快炒',
            note: '鲜嫩可口',
            forbidden: []
        },
        {
            id: 'v61',
            name: '豆豉鲮鱼油麦菜',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['油麦菜', '豆豉鲮鱼', '蒜'],
            time: '8分钟',
            difficulty: '简单',
            method: '油麦菜洗净，加豆豉鲮鱼炒香',
            note: '咸香下饭',
            forbidden: []
        },
        {
            id: 'v62',
            name: '金银蛋上汤苋菜',
            category: 'veg',
            tags: ['煮', '汤菜'],
            ingredients: ['苋菜', '皮蛋', '咸蛋', '蒜', '盐'],
            time: '15分钟',
            difficulty: '简单',
            method: '苋菜用高汤煮熟，加切碎的皮蛋咸蛋',
            note: '鲜美营养',
            forbidden: ['菠菜豆腐汤']
        },
        {
            id: 'v63',
            name: '烧茄子',
            category: 'veg',
            tags: ['烧', '下饭'],
            ingredients: ['茄子', '蒜', '生抽', '糖', '醋', '淀粉'],
            time: '20分钟',
            difficulty: '中等',
            method: '茄子切条过油，加调味汁烧入味',
            note: '软糯下饭',
            forbidden: ['地三鲜']
        },
        {
            id: 'v64',
            name: '鱼香茄子',
            category: 'veg',
            tags: ['烧', '辣'],
            ingredients: ['茄子', '豆瓣酱', '蒜', '生抽', '醋', '糖'],
            time: '20分钟',
            difficulty: '中等',
            method: '茄子切条过油，加鱼香汁烧入味',
            note: '鱼香味型',
            forbidden: ['地三鲜']
        },
        {
            id: 'v65',
            name: '肉末茄子',
            category: 'veg',
            tags: ['烧', '下饭'],
            ingredients: ['茄子', '肉末', '蒜', '生抽', '豆瓣酱'],
            time: '20分钟',
            difficulty: '简单',
            method: '茄子切条蒸熟，肉末炒熟，加茄子调味',
            note: '超级下饭',
            forbidden: ['地三鲜']
        },
        {
            id: 'v66',
            name: '地三鲜',
            category: 'veg',
            tags: ['炒', '东北菜'],
            ingredients: ['茄子', '土豆', '青椒', '生抽', '糖', '淀粉'],
            time: '25分钟',
            difficulty: '中等',
            method: '三种食材分别过油，回锅加调味汁炒匀',
            note: '经典东北菜',
            forbidden: ['地三鲜']
        },
        {
            id: 'v67',
            name: '东北乱炖',
            category: 'veg',
            tags: ['炖', '东北菜'],
            ingredients: ['土豆', '茄子', '豆角', '玉米', '五花肉', '生抽'],
            time: '40分钟',
            difficulty: '简单',
            method: '所有食材切块，加调料一起炖煮',
            note: '一锅出',
            forbidden: ['地三鲜']
        },
        {
            id: 'v68',
            name: '大乱炖',
            category: 'veg',
            tags: ['炖', '家常'],
            ingredients: ['白菜', '豆腐', '粉条', '五花肉', '生抽'],
            time: '40分钟',
            difficulty: '简单',
            method: '所有食材切块，加调料一起炖煮',
            note: '温暖家常',
            forbidden: []
        },
        {
            id: 'v69',
            name: '白菜炖粉条',
            category: 'veg',
            tags: ['炖', '家常'],
            ingredients: ['白菜', '粉条', '五花肉', '生抽', '姜'],
            time: '30分钟',
            difficulty: '简单',
            method: '白菜切块，粉条泡软，加肉一起炖煮',
            note: '冬日暖身',
            forbidden: []
        },
        {
            id: 'v70',
            name: '猪肉炖粉条',
            category: 'veg',
            tags: ['炖', '东北菜'],
            ingredients: ['五花肉', '粉条', '白菜', '生抽', '姜'],
            time: '60分钟',
            difficulty: '简单',
            method: '五花肉焯水炖煮，加白菜粉条继续炖',
            note: '东北名菜',
            forbidden: []
        },
        {
            id: 'v71',
            name: '小鸡炖蘑菇',
            category: 'veg',
            tags: ['炖', '东北菜'],
            ingredients: ['鸡肉', '蘑菇', '粉条', '生抽', '姜'],
            time: '60分钟',
            difficulty: '中等',
            method: '鸡肉焯水，加蘑菇一起炖煮',
            note: '鲜美滋补',
            forbidden: ['鸡汤']
        },
        {
            id: 'v72',
            name: '手撕包菜',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['包菜', '干辣椒', '蒜', '生抽', '醋'],
            time: '8分钟',
            difficulty: '简单',
            method: '包菜手撕成片，大火快炒，加醋调味',
            note: '爽脆下饭',
            forbidden: []
        },
        {
            id: 'v73',
            name: '干锅包菜',
            category: 'veg',
            tags: ['炒', '干锅'],
            ingredients: ['包菜', '五花肉', '干辣椒', '蒜', '生抽'],
            time: '15分钟',
            difficulty: '简单',
            method: '包菜干煸至软，加五花肉炒香',
            note: '干香下饭',
            forbidden: ['干锅']
        },
        {
            id: 'v74',
            name: '酸辣包菜',
            category: 'veg',
            tags: ['炒', '酸辣'],
            ingredients: ['包菜', '干辣椒', '醋', '生抽', '蒜'],
            time: '8分钟',
            difficulty: '简单',
            method: '包菜切片，大火快炒，加酸辣调味',
            note: '开胃下饭',
            forbidden: []
        },
        {
            id: 'v75',
            name: '炒合菜',
            category: 'veg',
            tags: ['炒', '家常'],
            ingredients: ['豆芽', '韭菜', '粉条', '鸡蛋', '生抽'],
            time: '15分钟',
            difficulty: '简单',
            method: '所有食材分别炒熟，混合调味',
            note: '春饼配菜',
            forbidden: []
        },
        {
            id: 'v76',
            name: '韭菜炒豆芽',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['韭菜', '豆芽', '盐'],
            time: '8分钟',
            difficulty: '简单',
            method: '韭菜切段，豆芽洗净，大火快炒',
            note: '清爽解腻',
            forbidden: []
        },
        {
            id: 'v77',
            name: '韭菜炒香干',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['韭菜', '香干', '生抽', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '韭菜切段，香干切片，大火快炒',
            note: '家常美味',
            forbidden: ['凉拌腐竹']
        },
        {
            id: 'v78',
            name: '韭菜炒千张',
            category: 'veg',
            tags: ['炒', '快手'],
            ingredients: ['韭菜', '千张', '生抽', '盐'],
            time: '10分钟',
            difficulty: '简单',
            method: '韭菜切段，千张切丝，大火快炒',
            note: '豆香浓郁',
            forbidden: ['凉拌腐竹']
        },
        {
            id: 'v79',
            name: '韭菜盒子',
            category: 'veg',
            tags: ['煎', '主食'],
            ingredients: ['韭菜', '鸡蛋', '粉条', '面粉', '盐'],
            time: '40分钟',
            difficulty: '中等',
            method: '韭菜鸡蛋粉条做馅，包盒子煎至金黄',
            note: '北方主食',
            forbidden: []
        },
        {
            id: 'v80',
            name: '韭菜鸡蛋饼',
            category: 'veg',
            tags: ['煎', '早餐'],
            ingredients: ['韭菜', '鸡蛋', '面粉', '盐'],
            time: '20分钟',
            difficulty: '简单',
            method: '韭菜切碎拌入面糊，加鸡蛋，煎至两面金黄',
            note: '早餐首选',
            forbidden: []
        },
        {
            id: 'v81',
            name: '葱花饼',
            category: 'veg',
            tags: ['煎', '主食'],
            ingredients: ['面粉', '葱', '盐', '油'],
            time: '30分钟',
            difficulty: '中等',
            method: '面团擀开抹油撒葱花，卷起再擀，煎至金黄',
            note: '香酥多层',
            forbidden: []
        },
        {
            id: 'v82',
            name: '手抓饼',
            category: 'veg',
            tags: ['煎', '主食'],
            ingredients: ['手抓饼胚', '鸡蛋', '生菜', '番茄酱'],
            time: '10分钟',
            difficulty: '简单',
            method: '饼胚煎至金黄，加蛋和配菜卷起',
            note: '街头美味',
            forbidden: []
        },
        {
            id: 'v83',
            name: '煎饼果子',
            category: 'veg',
            tags: ['煎', '早餐'],
            ingredients: ['面粉', '鸡蛋', '油条', '甜面酱', '葱'],
            time: '15分钟',
            difficulty: '中等',
            method: '面糊摊饼，加鸡蛋翻面，抹酱放油条卷起',
            note: '天津特色',
            forbidden: []
        },
        {
            id: 'v84',
            name: '鸡蛋灌饼',
            category: 'veg',
            tags: ['煎', '早餐'],
            ingredients: ['饼胚', '鸡蛋', '生菜', '甜面酱'],
            time: '15分钟',
            difficulty: '中等',
            method: '饼胚鼓起戳洞灌入鸡蛋，煎熟加配菜',
            note: '早餐热门',
            forbidden: []
        },
        {
            id: 'v85',
            name: '葱油饼',
            category: 'veg',
            tags: ['煎', '主食'],
            ingredients: ['面粉', '葱', '油', '盐'],
            time: '30分钟',
            difficulty: '中等',
            method: '面团抹葱油，卷起再擀，煎至金黄',
            note: '香酥可口',
            forbidden: []
        },
        {
            id: 'v86',
            name: '锅贴',
            category: 'veg',
            tags: ['煎', '主食'],
            ingredients: ['饺子皮', '韭菜', '鸡蛋', '粉条', '盐'],
            time: '30分钟',
            difficulty: '中等',
            method: '包饺子状，煎至底部金黄，加水焖熟',
            note: '外酥里嫩',
            forbidden: []
        },
        {
            id: 'v87',
            name: '生煎包',
            category: 'veg',
            tags: ['煎', '主食'],
            ingredients: ['面粉', '猪肉馅', '葱', '姜', '生抽'],
            time: '60分钟',
            difficulty: '困难',
            method: '包馅发酵，煎至底部金黄，加水焖熟',
            note: '上海特色',
            forbidden: []
        },
        {
            id: 'v88',
            name: '水煎包',
            category: 'veg',
            tags: ['煎', '主食'],
            ingredients: ['面粉', '韭菜', '鸡蛋', '粉条', '盐'],
            time: '50分钟',
            difficulty: '中等',
            method: '包馅，煎至底部金黄，加水焖熟',
            note: '北方特色',
            forbidden: []
        },
        {
            id: 'v89',
            name: '包子',
            category: 'veg',
            tags: ['蒸', '主食'],
            ingredients: ['面粉', '猪肉馅', '葱', '姜', '生抽'],
            time: '90分钟',
            difficulty: '中等',
            method: '发面包馅，蒸20分钟',
            note: '早餐必备',
            forbidden: []
        },
        {
            id: 'v90',
            name: '馒头',
            category: 'veg',
            tags: ['蒸', '主食'],
            ingredients: ['面粉', '酵母', '水'],
            time: '90分钟',
            difficulty: '简单',
            method: '发面整形，蒸20分钟',
            note: '北方主食',
            forbidden: []
        },
        {
            id: 'v91',
            name: '花卷',
            category: 'veg',
            tags: ['蒸', '主食'],
            ingredients: ['面粉', '葱', '油', '盐'],
            time: '90分钟',
            difficulty: '中等',
            method: '发面抹葱油，卷起切段，拧花蒸制',
            note: '层次丰富',
            forbidden: []
        },
        {
            id: 'v92',
            name: '饺子',
            category: 'veg',
            tags: ['煮', '主食'],
            ingredients: ['面粉', '猪肉馅', '白菜', '葱', '姜', '生抽'],
            time: '60分钟',
            difficulty: '中等',
            method: '和面擀皮包馅，煮熟',
            note: '北方年节',
            forbidden: []
        },
        {
            id: 'v93',
            name: '馄饨',
            category: 'veg',
            tags: ['煮', '主食'],
            ingredients: ['馄饨皮', '猪肉馅', '葱', '姜', '生抽', '紫菜'],
            time: '40分钟',
            difficulty: '中等',
            method: '包馅，煮制，配紫菜汤',
            note: '早餐首选',
            forbidden: []
        },
        {
            id: 'v94',
            name: '面条',
            category: 'veg',
            tags: ['煮', '主食'],
            ingredients: ['面条', '青菜', '生抽', '香油', '葱'],
            time: '10分钟',
            difficulty: '简单',
            method: '煮面，加青菜，调味',
            note: '简单快捷',
            forbidden: []
        },
        {
            id: 'v95',
            name: '阳春面',
            category: 'veg',
            tags: ['煮', '主食'],
            ingredients: ['面条', '葱', '生抽', '香油', '猪油'],
            time: '10分钟',
            difficulty: '简单',
            method: '煮面，碗底放调料，加面汤和面',
            note: '上海特色',
            forbidden: []
        },
        {
            id: 'v96',
            name: '担担面',
            category: 'veg',
            tags: ['拌', '主食', '辣'],
            ingredients: ['面条', '肉末', '辣椒油', '花椒粉', '芝麻酱', '生抽'],
            time: '20分钟',
            difficulty: '中等',
            method: '煮面，加肉末和调味汁拌匀',
            note: '四川名吃',
            forbidden: []
        },
        {
            id: 'v97',
            name: '炸酱面',
            category: 'veg',
            tags: ['拌', '主食'],
            ingredients: ['面条', '肉末', '甜面酱', '黄瓜丝', '豆芽'],
            time: '30分钟',
            difficulty: '简单',
            method: '炒炸酱，煮面，配黄瓜丝豆芽拌匀',
            note: '北京特色',
            forbidden: []
        },
        {
            id: 'v98',
            name: '热干面',
            category: 'veg',
            tags: ['拌', '主食'],
            ingredients: ['碱面条', '芝麻酱', '生抽', '醋', '辣椒油', '萝卜干'],
            time: '15分钟',
            difficulty: '简单',
            method: '煮面，加芝麻酱和调料拌匀',
            note: '武汉特色',
            forbidden: []
        },
        {
            id: 'v99',
            name: '凉皮',
            category: 'veg',
            tags: ['拌', '小吃'],
            ingredients: ['凉皮', '黄瓜丝', '豆芽', '蒜', '醋', '辣椒油'],
            time: '15分钟',
            difficulty: '简单',
            method: '凉皮切条，加配菜调料拌匀',
            note: '夏日解暑',
            forbidden: ['凉拌黄瓜']
        },
        {
            id: 'v100',
            name: '凉粉',
            category: 'veg',
            tags: ['拌', '小吃'],
            ingredients: ['凉粉', '黄瓜丝', '蒜', '醋', '辣椒油'],
            time: '10分钟',
            difficulty: '简单',
            method: '凉粉切块，加配菜调料拌匀',
            note: '清爽解暑',
            forbidden: ['凉拌黄瓜']
        }
    ]
};

// 现有食材列表
const AVAILABLE_INGREDIENTS = {
    refrigerated: [
        '蒜苔', '西红柿', '鸡蛋', '西葫芦', '青椒', 
        '白菜', '上海青', '口蘑', '芦笋', '培根', 
        '蟹味菇', '豆腐', '菠菜'
    ],
    frozen: [
        '鱿鱼', '鳕鱼', '三文鱼', '汤圆', 
        '肥牛卷', '乌鸡', '葱姜排骨', '牛肉', '猪肚'
    ]
};

// 禁忌食材/菜品
const FORBIDDEN_ITEMS = [
    '凉拌黄瓜',
    '糖醋里脊',
    '菠菜豆腐汤',
    '带鱼',
    '荷兰豆',
    '鲫鱼',
    '鱼汤',
    '回锅肉',
    '藕',
    '鸡汤',
    '鸭汤',
    '鱼汤',
    '干锅',
    '地三鲜',
    '西湖牛肉羹',
    '红烧狮子头',
    '凉拌腐竹',
    '各种荤汤'
];

// 从localStorage加载保存的禁忌
function loadForbiddenFromStorage() {
    const saved = localStorage.getItem('xutao_meal_planner_forbidden');
    return saved ? JSON.parse(saved) : [...FORBIDDEN_ITEMS];
}

// 保存禁忌到localStorage
function saveForbiddenToStorage(forbidden) {
    localStorage.setItem('xutao_meal_planner_forbidden', JSON.stringify(forbidden));
}

// 检查菜品是否包含禁忌
function hasForbiddenDish(dishName, forbiddenList) {
    return forbiddenList.some(forbidden => 
        dishName.toLowerCase().includes(forbidden.toLowerCase()) ||
        forbidden.includes(dishName)
    );
}

// 获取可用菜品（排除禁忌）
function getAvailableDishes(category, forbiddenList) {
    const dishes = DISH_DATABASE[category] || [];
    return dishes.filter(dish => !hasForbiddenDish(dish.name, forbiddenList));
}

// 根据现有食材推荐菜品
function getDishesByIngredients(availableIngredients, category, forbiddenList) {
    const dishes = getAvailableDishes(category, forbiddenList);
    
    return dishes.map(dish => {
        const matchedIngredients = dish.ingredients.filter(ing => 
            availableIngredients.some(avail => 
                ing.includes(avail) || avail.includes(ing)
            )
        );
        const matchRate = matchedIngredients.length / dish.ingredients.length;
        
        return {
            ...dish,
            matchedIngredients,
            matchRate,
            canMake: matchRate >= 0.5 // 50%以上食材匹配即可做
        };
    }).sort((a, b) => b.matchRate - a.matchRate);
}
